project:
  type: website

website:
  title: "posit::conf(2023)"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "Workshops"
        file: workshop.qmd
      - text: "Talks"
        file: talks.qmd
        
  sidebar:
    - id: workshops
      title: "Workshops"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - workshops.qmd
        - day1.qmd
        - day2.qmd
        
    - id: talks
      title: "Talks"
      style: "docked"
      background: light
      contents: 
        - talks.qmd
        - day3.qmd
        - day4.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

