project:
  type: website

website:
  title: "posit::conf(2023)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - sidebar:days
  sidebar:
    - id: days
      title: "days"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - day1.qmd
        - day2.qmd
        - day3.qmd
        - day4.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

