project:
  type: website

website:
  title: "posit::conf(2023)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - text: About
      - href: workshops.qmd
      - text: Workshops
      - sidebar:workshops
      - sidebar:talks
  sidebar:
    - id: workshops
      title: "Workshops"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - day1.qmd
        - day2.qmd
        
    - id: talks
      title: "Talks"
      style: "docked"
      background: light
      contents: 
        - day3.qmd
        - day4.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

