project:
  type: website
  output-dir: output

website:
  title: "posit::conf(2023)"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "Workshops"
        file: workshops.qmd
      - text: "Talks"
        file: talks.qmd
      - text: "Chicago"
        file: chicago.qmd

  sidebar:
    - id: workshops
      title: "Workshops"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - workshops.qmd
        - day1.qmd
        - day2.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

