---
title: "Talks"
---

## Keynotes

#### From Data Confusion to Data Intelligence

*Elaine McVey*, Senior Director of Analytics, Chief David Meza, Head of *Analytics* - Human Capital, NASA

Data science teams operate in a unique environment, much different than the IT or software development life cycle. Hope from executives for the impact of data science is extremely high! Understanding of how to make data science efforts successful is very low! This creates an interesting set of organizational challenges for data and analytics teams. These are particularly clear when data science is being introduced at new companies, but plays out at organizations of all sizes. So, how do we navigate this dynamic? We'll share some strategies for success.

-   collect formated data if you can!!!!

#### A hackers guide to open source LLMs

*Jeremy Howard*, Founding Researcher, fast.ai, Kaggle

Everyone is talking about open source large language models (LLMs), but if you want to get hacking with them, it's not easy to get started. Things are moving so quickly -- especially since the release of the breakthrough Llama2 models! In this talk Jeremy will explain the landscape, what you need to get started, and demonstrate what's possible with the latest tools.

[Live Captioned](https://p3.3playmedia.com/live-asr-client-v1/external_webpage_with_captions.html?key=275CbvNYmT0UjdlO&show_accessibility_menu=true&show_complete_transcript=true&stream_start=1695137100&use_uppercase=0) - and the Notebook.

<https://github.com/fastai/lm-hackers/blob/main/lm-hackers.ipynb>

-   give your model context

-   LoRA - low rank adaptation, might be useful to reduce training times for large models, didn;t go into it.

## Quarto

**Reproducible Manuscripts with Quarto\
***Mine Çetinkaya-Rundel*, Developer Educator + Professor of the Practice, Posit, PBC

In this talk, we present a new capability in Quarto that provides a straightforward and user-friendly approach to creating truly reproducible manuscripts that are publication-ready for submission to popular journals. This new feature, Quarto manuscripts, includes the ability to produce a bundled output containing a standardized journal format, source documents, source computations, referenced resources, and execution information into a single bundle that is ingested into journal review and production processes. We'll demo how Quarto manuscripts work and how you can incorporate them into your current manuscript development process as well as touch on pain points in your current workflow that Quarto manuscripts help alleviate.\
[Slides](https://mine.quarto.pub/manuscripts-conf23/#/title-slide)

**What's New in Quarto?**

*Charlotte Wickham*, Developer Educator, Quarto, Posit, PBC\
It's been over a year since Quarto 1.0, an open-source scientific and technical publishing system, was announced at rstudio::conf(2022). In this talk, I'll highlight some of the improvements to Quarto since then. You'll learn about new formats, options, tools, and ways to supercharge your content. And, if you haven't used Quarto yet, come to see some reasons to try it out.\
[Charlotte's Slides](https://cwickham.github.io/whats-new-in-quarto/#/title-slide)

Quarto 1.4 will have ability to embed/link images and chunks from Python Notebooks.

\##### Quarto Resources\
<https://andreaczhang.github.io/qtwAcademic/>\
<https://quarto.org/docs/publishing/>\
<https://jadeynryan.github.io/2023_posit-parameterized-quarto/#/title-slide>

## Shiny

**Using R, Python, and Cloud Infrastructure to Battle Aquatic Invasive Species\
***Nicholas Snellgrove*, Tech Lead, [Epi-interactive](https://www.epi-interactive.com/)\
*Uli Muellner*, Managing Director, [Epi-interactive](https://www.epi-interactive.com/)

Invasive species are a huge threat to lake ecosystems in Minnesota. With over 10,000 water bodies across the state, having up-to-date data and decision support is critical. Researchers at the University of Minnesota have created four complex R and Python models to support lake managers, all pulled together and presented with the most recent infestation data available. Come along with us to see how we connected these models in the AIS Explorer, a decision support application built in Shiny to help prioritize risks and placing watercraft inspectors, using tools like OCPU and cloud toolings like Lambda, EventBridge and AWS S3.

shiny without a server - <https://github.com/jcheng5/posit-conf-2023-shinylive>

## Other Resources

Colour - <http://web-accessibility.carnegiemuseums.org/design/color/> https://github.com/pncnmnp/typst-poster

Publish to Confluence\
https://quarto.org/docs/publishing/confluence.html
